/**
 * Generates src/data/generated/{fighters,events}.summary.ts — the
 * lightweight FighterSummary/EventSummary projections that ship to every
 * page except a record's own profile (see src/types/index.ts's doc
 * comment on FighterSummary, and src/lib/loadContent.ts).
 *
 * Run via `npm run generate:summaries` (wired into `predev` and as the
 * first step of `npm run build`). The generated files are committed —
 * the repo builds without running this — and scripts/validate-content.ts
 * fails the build if they've drifted from what regenerating would
 * produce.
 *
 * Uses Vite's own SSR module loader (not a hand-rolled parser) so it
 * resolves the `@/types` alias exactly like the real app, and reads the
 * data straight from the typed source files.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { createServer, type ViteDevServer } from 'vite';
import { pickEventSummary, pickFighterSummary } from './lib/summaries.ts';
import type { FreedomFighter, HistoricalEvent } from '../src/types/index.ts';

async function loadArrayExport<T>(vite: ViteDevServer, path: string): Promise<T[]> {
  const mod = await vite.ssrLoadModule(path);
  const arr = Object.values(mod).find((v): v is T[] => Array.isArray(v));
  if (!arr) throw new Error(`generate-summaries: no array export found in ${path}`);
  return arr;
}

async function sourceFileBySlug<T extends { slug: string }>(vite: ViteDevServer, dir: string): Promise<Record<string, string>> {
  const map: Record<string, string> = {};
  const files = readdirSync(dir).filter((f) => f.endsWith('.ts') && f !== 'index.ts');
  for (const file of files) {
    const name = file.replace(/\.ts$/, '');
    const arr = await loadArrayExport<T>(vite, `/${dir}/${file}`);
    for (const record of arr) map[record.slug] = name;
  }
  return map;
}

function writeGeneratedFile(path: string, header: string, typeImport: string, exports: { name: string; type: string; value: unknown }[]) {
  const body = exports.map(({ name, type, value }) => `export const ${name}: ${type} = ${JSON.stringify(value, null, 2)};`).join('\n\n');
  writeFileSync(path, `${header}\n\n${typeImport}\n\n${body}\n`);
}

const vite = await createServer({ server: { middlewareMode: true }, appType: 'custom', logLevel: 'silent' });

const fighters = await loadArrayExport<FreedomFighter>(vite, '/src/data/fighters/index.ts');
const events = await loadArrayExport<HistoricalEvent>(vite, '/src/data/events/index.ts');
const fighterSourceFile = await sourceFileBySlug<FreedomFighter>(vite, 'src/data/fighters');
const eventSourceFile = await sourceFileBySlug<HistoricalEvent>(vite, 'src/data/events');

await vite.close();

const GENERATED_HEADER = '// AUTO-GENERATED by scripts/generate-summaries.ts — do not edit by hand.\n// Run `npm run generate:summaries` to regenerate.';

writeGeneratedFile('src/data/generated/fighters.summary.ts', GENERATED_HEADER, "import type { FighterSummary } from '@/types';", [
  { name: 'fighterSummaries', type: 'FighterSummary[]', value: fighters.map(pickFighterSummary) },
  { name: 'fighterSourceFile', type: 'Record<string, string>', value: fighterSourceFile },
]);
writeGeneratedFile('src/data/generated/events.summary.ts', GENERATED_HEADER, "import type { EventSummary } from '@/types';", [
  { name: 'eventSummaries', type: 'EventSummary[]', value: events.map(pickEventSummary) },
  { name: 'eventSourceFile', type: 'Record<string, string>', value: eventSourceFile },
]);

console.log(`Generated summaries for ${fighters.length} fighters and ${events.length} events.`);
